---
kind: Service
apiVersion: v1
metadata:
  name: firstdocker
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30005
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  labels:
    app: firstdocker-label-text
  name: firstdocker
spec:
  replicas: 5
  selector:
      matchLabels:
        app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: engp8691/firstdocker:v1
          ports:
            - containerPort: 8080